---
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli/
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w'
      - -X github.com/drewstinnett/taskpoet/cli/cmd.date={{ .CommitTimestamp }}
      - -X github.com/drewstinnett/taskpoet/cli/cmd.version={{ .Tag }}
      - -X github.com/drewstinnett/taskpoet/cli/cmd.commit={{ .ShortCommit }}
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'taskpoet'
archives:
  - format: tar.gz
    name_template: 'taskpoet-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: macOS
checksum:
  name_template: 'taskpoet-{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true

brews:
  - name: 'taskpoet'
    skip_upload: true
    tap:
      owner: drewstinnett
      name: homebrew-taskpoet
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Alternative to the awesome TaskWarrior, but in Go, with some additional stuff I find useful"
    homepage: "https://github.com/drewstinnett/taskpoet"
    license: BSD-2-Clause
    caveats: |
      Add the following in your ~/.zshrc or ~/.profile for faster typin':

        alias tp="#{opt_bin}/taskpoet"
