site_name: TaskPoet
docs_dir: docs
site_dir: public
repo_url: https://github.com/drewstinnett/taskpoet
edit_uri: https://github.com/drewstinnett/taskpoet/edit/main/docs
theme:
  name: material
  icon:
    logo: material/feather
  features:
    - content.action.edit
    - content.code.select
    - content.code.copy
    - content.tabs.link
nav:
  - Overview: index.md
  - Install: install.md
  - Coming from TaskWarrior: taskwarrior.md
  - Recurring tasks: recurring.md
  - Configuration: configuration.md
  - Themes: themes.md
  - Upgrading from v0.x: upgrading.md
