---
name: Security Scans
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "America/New_York"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - id: govulncheck
        uses: golang/govulncheck-action@v1
